---
- hosts: local
  become: true
  become_method: sudo
  vars:
    arduino_port: /dev/ttyACM0  # communication port (usually /dev/ttyACM*)
    arduino_project:
      - blink
      - switch
    arduino_model: uno
    arduino: 161
    arduino_dir: /usr/share/arduino
    arduino_avr_txt: /hardware/archlinux-arduino/avr/boards.txt
    arduino_variant: /hardware/archlinux-arduino/avr/variants/standard
    arduino_core: /hardware/archlinux-arduino/avr/cores/arduino
  tasks:

  - name: Install arduino software
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - arduino
      - arduino-docs
      - arduino-avr-core
    tags:
      - setup

  - name: Add "{{ lookup('env','USER') }}" to uucp and lock groups
    user:
      name: "{{ lookup('env','USER') }}"
      groups: "{{ item }}"
      append: yes
    with_items:
      - uucp
      - lock
    tags:
      - "setup"

  - name: Generate Makefile
    # https://github.com/tomswartz07/arduino-makefile/blob/master/Makefile
    template:
      src: Makefile.j2
      dest: "{{ item }}/Makefile"
      mode: 0644
    become: false
    with_items: "{{ arduino_project }}"
